apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: trino-catalog
  namespace: olm
spec:
  sourceType: grpc
  grpcPodConfig:
    securityContextConfig: restricted
  image: registry.cn-hangzhou.aliyuncs.com/luwei-dev/trino-operator-catalog:latest
  displayName: trino catalog
  publisher: zncdatadev
  updateStrategy:
    registryPoll:
      interval: 5m